sensu/uchiwa

public/js/filters.js, public/partials/stashes/index.html, test/karma/filters-spec.js
It is possible that not all stashes are 'silence'. This adds a column to display the stash type.
=> Display stash type

.gitignore, uchiwa.go, uchiwa/config.go, uchiwa/dc.go, uchiwa/server.go
In light of this recent pull request (https://github.com/sensu/uchiwa/pull/244), the goji/httpauth authentication library might not work if we plan to add additional authentication methods.
This pull request remove all dependencies to the previous library and implement the palourde/auth, which use a JSON Web Token to authenticate the users.
=> [WIP] Use JSON Web Tokens (JWT)

uchiwa/events.go
This PR is required by https://github.com/sensu/uchiwa-web/pull/12 and is related to https://github.com/sensu/uchiwa/issues/264
This PR creates a new property on events, client.acknowleged, which indicates the silence status of the event's source (client).
=> Filter silenced client events

uchiwa/config/config.go, uchiwa/config/config_test.go
Fix https://github.com/sensu/uchiwa/issues/279
=> Remove invalid characters from DC name

.gitignore, uchiwa.go, uchiwa/auth/auth.go, uchiwa/auth/handlers.go, uchiwa/auth/token.go, uchiwa/config/config.go, uchiwa/config/config_test.go, uchiwa/server.go, uchiwa/structs/structs.go
Fix https://github.com/sensu/uchiwa/issues/394
- Load the RSA keys provided in the config file (TODO: docs). Fallback to automatic generation in case of problems.
- Fix a [vulnerability](https://auth0.com/blog/2015/03/31/critical-vulnerabilities-in-json-web-token-libraries/) in the JWT library
- Upgrade to 2048 RSA keys for JWT signature
=> Support the use of static RSA keys for JWT signature

.dockerignore, Dockerfile
docker images | grep uchiwa
uchiwa              alpine              8f1ecc470f0f        2 minutes ago       301 MB
uchiwa              latest              1585aac90bf3        23 minutes ago      824.1 MB
Shrunk the total image size by more than half and also decreased the image build time.
For #462
=> Convert docker image to use alpine base

uchiwa/auth/drivers.go, uchiwa/auth/drivers_test.go
Fixes #448.
Also adds a thin test layer for the affected code.
This is the first Go code I ever wrote. Please bear with me. :)
A few questions:
- is the new dependency fine?
- is the test ok?
Also, I'm using the more or less widely known {crypt} prefix to indicate we should treat a password as crypted. I see that the user data structure has a separate field for a hashed/salted password, but this a) looks like it has implications to the Enterprise edition and b) I didn't want to make too much of an invasive change.
Let me know if this needs changes or is otherwise not good enough. 
Cheers,
Christian
=> Add support for crypt()ed passwords.

uchiwa/daemon/events.go
Do not trust the `silenced` & `silenced_by` attributes provided in Sensu events since they might be confusing for the users.
https://github.com/sensu/uchiwa/issues/602
We already use the `helpers.IsCheckSilenced` function for the client view.
=> Overwrite silence & silenced_by attributes in Sensu events. Fixes #602

uchiwa/logger/logger.go
Added `html.EscapeString()` to `fmt.Println(err.Error())`. This change may also be appropriate for `fmt.Println(string(data))` but would warrant testing I'm not prepared/setup to do.
Issue #618 
Prevents 2 potential reflected XSS points identified by Fortify
logger.go was built locally
=> Issue #618 fix

uchiwa/logger/logger.go, uchiwa/logger/logger_test.go
Implements a mutex in the logger package to control access to the main Logger object used in the `print` function.
#621 
Removes the race condition reported in #621 
I've ran both my new and existing tests and ensured that they all pass.
=> remove race condition on logger package

fixtures/users/config_users.json, public/index.html, uchiwa/config/config.go, uchiwa/config/config_test.go, uchiwa/config/structs.go, uchiwa/server.go
- Remove the angular-mass-autocomplete dependency for the HTML5 datalist
- Add the angular-moment-picker dependency as the datetime picker
- Add the SilenceDurations attribute in UsersOptions in order to customize durations
Resolves https://github.com/sensu/uchiwa/issues/644.
Depends on https://github.com/sensu/uchiwa-web/pull/143.
Unit & manual testing.
=> Silenced refactoring

public/index.html, uchiwa/client.go, uchiwa/filters/filters.go, uchiwa/sensu/clients.go, uchiwa/server.go
Allows editing of proxy clients through the Sensu client registry, directly from the UI. Only applies to clients with `keepalives:false`.
Fixes https://github.com/sensu/uchiwa/issues/651.
Depends on https://github.com/sensu/uchiwa-web/pull/144
Be able to easily modify proxy clients.
Unit tests & manual testing.
=> Add support for editing the Sensu client registry

uchiwa/daemon/daemon.go, uchiwa/daemon/datacenters.go, uchiwa/datacenter.go, uchiwa/server.go, uchiwa/structs/structs.go
We add a new datacenter view, accessible from the datacenters view, in order to access new information about the Sensu servers available since [Sensu 0.28](https://sensuapp.org/docs/0.28/overview/changelog.html#core-v0-28-0-changes).
The `Datacenter` structure exposed in the /datacenters endpoint has been modified; the `Stats` attribute is now called `Metrics`.
We also add additional debug information when Sensu API does not respond properly.
Fixes https://github.com/sensu/uchiwa/issues/652
Depends on https://github.com/sensu/uchiwa-web/pull/145
Display Sensu servers information
=> Add a datacenter view to access information about the Sensu servers

uchiwa/config/config.go, uchiwa/config/config_test.go, uchiwa/config/structs.go
Adjust the `config` package for the enterprise Console.
https://github.com/sensu/sensu-enterprise-dashboard/issues/79
=> [enterprise] Add support for multiple LDAP servers

uchiwa/server.go
Prevent Clickjacking by adding the X-Frame-Options response header to all static content.
https://www.owasp.org/index.php/Clickjacking_Defense_Cheat_Sheet
=> Prevent clickjacking with X-Frame-Options header

uchiwa/check.go, uchiwa/client.go, uchiwa/daemon/events.go, uchiwa/helpers/helpers.go, uchiwa/helpers/helpers_test.go
A check could be silenced based on the clients subscriptions and not only its own subscribers.
Fixes https://github.com/sensu/uchiwa/issues/689
Unit tests.
=> Consider clients subscriptions when determining if a check is silenced

uchiwa/config/structs.go, uchiwa/main.go, uchiwa/sensu/request.go, uchiwa/sensu/sensu.go
- Use io.ReadFull instead of ioutil.ReadAll when reading Sensu API responses
- Add advanced configuration settings for Sensu APIs HTTP clients
N/A
Prevent EOF errors
Manual testing!
=> Various optimizations

uchiwa/config/structs.go, uchiwa/logger/logger.go, uchiwa/main.go, uchiwa/sensu/clients.go, uchiwa/sensu/events.go, uchiwa/sensu/request.go, uchiwa/sensu/sensu.go
- Add tracing attribute for HTTP client tracing
- Use pagination on Sensu API events endpoint
N/A
Add tooling for additional debug of Sensu APIs errors
=>  Add tracing attribute for HTTP client tracing

build/assets/etc/logrotate.d/uchiwa
It adds a logrotate configuration to _DEB_ and _RPM_ packages.
Closes https://github.com/sensu/uchiwa/issues/703
It prevents the log files from filling up the disk space.
Tested on Debian by manually running logrotate with this configuration.
=> Provide a logrotate configuration in packages

uchiwa/sensu/request.go
It makes sure we validate the content length of the response before trying to read its body
Closes https://github.com/sensu/uchiwa/issues/725
=> Prevent makeslice: len out of range when using the response content length

uchiwa/config/config.go, uchiwa/config/structs.go, uchiwa/config/tls.go, uchiwa/server.go
Signed-off-by: Simon Plourde <simon.plourde@gmail.com>
The TLS cipher suite and TLS minimal version are now configurable.
Additionally, the `TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA` & `TLS_RSA_WITH_3DES_EDE_CBC_SHA` ciphers have been removed from the default suite.
Closes https://github.com/sensu/uchiwa/issues/688
Fix SWEET32 vulnerability
=> Add configurable TLS config

uchiwa/config/structs.go
Signed-off-by: Simon Plourde <simon.plourde@gmail.com>
It prevents the `unsupported type: func() time.Time` error when serializing the config to JSON.
N/A
=> Do not serialize the TLS config

build/Dockerfile, build/tests.sh
It's really helpful to have an ability to build uchiwa package
in docker image, without installing additional dependencies on
host system
Allow to build uchiwa package in docker
We need to have ability for simple uchiwa packaging
No changes in code itself, just additional feature with two docker commands:
* build docker image
* build package with docker image
- [+] New feature (non-breaking change which adds functionality)
- [+] My change requires a change to the documentation.
- [+] I have updated the documentation accordingly.
- [+] I have read the **CONTRIBUTING** document.
- [+] I have added tests to cover my changes.
- [+] All new and existing tests passed.
=> Allow to build uchiwa packages in docker

.travis.yml, build/travis.sh, uchiwa/client.go, uchiwa/client_test.go, uchiwa/helpers/helpers.go, uchiwa/helpers/helpers_test.go
When we determine if a check is silenced, we need to ensure that the client is actually subscribed to that check!
Closes https://github.com/sensu/uchiwa/issues/755
Added specific unit test for that case
=> Validate both check & client subscriptions when silencing

build/pkg_scripts/deb/postinst, build/pkg_scripts/rpm/post
Ensures the logrotate config permissions are `644` after installation.
Closes https://github.com/sensu/uchiwa/issues/757
=> Fix logrotate config permissions

build/pkg_scripts/rpm/post
Signed-off-by: Simon Plourde <simon.plourde@gmail.com>
It fixes a bug when installation 1.1.3-1 RPM packages
Closes https://github.com/sensu/uchiwa/issues/760
=> Fix syntax error in RPM post script

uchiwa/daemon/clients.go
Signed-off-by: Justin Kolberg <amd.prophet@gmail.com>
Adds concurrency to the `buildClients()` method.
N/A
The `buildClients()` method takes a significant amount of time to complete with a large number of clients & events. For example, with 18000 clients & events it was taking `2m1.553801286s` to complete. With these changes it now takes `21.951286761s`.
Added some log lines to benchmark performance. Started Uchiwa & verified data was still getting populated.
=> Add concurrency to buildClients()

uchiwa/daemon/daemon.go
Signed-off-by: Justin Kolberg <amd.prophet@gmail.com>
Fixes a bug where a maximum of one silenced entry will ever appear.
Fixes https://github.com/sensu/uchiwa/issues/785
N/A
Tested locally. More than one silenced entry will now appear.
=> Fix for only one silenced entry showing up

uchiwa/daemon/daemon.go
Signed-off-by: Justin Kolberg <amd.prophet@gmail.com>
Fixes a segfault when there are one or more unresponsive APIs.
Fixes https://github.com/sensu/uchiwa/issues/786.
Uchiwa should not be segfaulting.
Tested locally by stopping the Sensu API. Uchiwa backend no longer segfaults and errors are appropriately displayed on the frontend.
=> Fix segfault on unresponsive APIs

README.md
Update links in the README.md to reflect new documentation site
Closes #790 
We merged the Uchiwa documentation into the sensu-docs project, which broke these links. It is good to fix broken links.
Markdown preview looks good.
=> update docs.uchiwa.io links to use new paths on docs.sensu.io

CHANGELOG.md, uchiwa/client.go, uchiwa/sensu/clients.go, uchiwa/server.go
Signed-off-by: Simon Plourde <simon.plourde@gmail.com>
It adds support for client invalidation when deleting a single or multiple clients.
Requires https://github.com/sensu/uchiwa-web/pull/24
Closes https://github.com/sensu/sensu-enterprise-dashboard/issues/132
=> Add client invalidation

vendor/github.com/mitchellh/mapstructure/README.md, vendor/github.com/mitchellh/mapstructure/decode_hooks.go, vendor/github.com/mitchellh/mapstructure/error.go, vendor/github.com/mitchellh/mapstructure/go.mod, vendor/github.com/mitchellh/mapstructure/mapstructure.go, vendor/vendor.json
This PR updates the vendored mapstructure dependency to version 1.0.0, which includes a fix for a race condition that can lead to segfaults: mitchellh/mapstructure@7869cdbd0bea0c846ad7b8b09bac31f34875aa11
#798
This change fixes a segfault that occurs from simply leaving Uchiwa running.
All unit tests pass. I'll build new RPMs and test them in our environment.
=> vendor: Update mapstructure to 1.0.0

uchiwa/daemon/daemon.go, uchiwa/daemon/helpers.go, uchiwa/main.go, uchiwa/sensu/aggregates.go, uchiwa/sensu/checks.go, uchiwa/sensu/clients.go, uchiwa/sensu/events.go, uchiwa/sensu/loadbalancing.go, uchiwa/sensu/methods.go, uchiwa/sensu/request.go, uchiwa/sensu/silenced.go, uchiwa/sensu/stashes.go, uchiwa/server.go
This PR introduces a couple of changes around the fetcher, in order to optimize the operations and prevent data races:
- Prevent a data race around the APIs list shuffling
- Prevent data races when accessing the "snapshot" data of a datacenter
- Use a RWMutex so the API can request multiple read locks simultaneously 
- Refactoring of the fetcher's goroutines coordination so they can be canceled (bt using a `context` all the way up to the HTTP client) and and the errors can be sent over a channel instead
- Make the logs a bit less verbose in the `warning` level; only log the first error with an API at this level and log the rest as `debug`
It fixes some issues reported by one of our customer.
=> Daemon optimizations

uchiwa/daemon/daemon.go, uchiwa/daemon/helpers.go, uchiwa/daemon/subscriptions.go, uchiwa/main.go, uchiwa/sensu/info.go, uchiwa/sensu/loadbalancing.go, uchiwa/sensu/sensu.go
Adds the ability to mark an API as healthy/unhealthy. Uchiwa will only make requests to APIs marked as healthy. APIs marked as unhealthy will be watched be a goroutine and marked as healthy once they respond with an HTTP 2xx error.
Fixes #811.
See #811.
I've tested with the following configuration:
```
{
"sensu": [
{
"name": "Site 1",
"host": "127.0.0.1",
"port": 4567
},
{
"name": "Site 2",
"host": "127.0.0.1",
"port": 4567
},
{
"name": "Site 2",
"host": "10.0.1.11",
"port": 4567
}
],
"uchiwa": {
"host": "0.0.0.0",
"port": 3000,
"refresh": 5,
"loglevel": "warn"
}
}
```
I've tested Uchiwa with one or both APIs down, one API up and one API down, and then starting the APIs that were down to see APIs marked as healthy.
=> Support marking APIs as healthy/unhealthy

uchiwa/sensu/loadbalancing.go, uchiwa/sensu/methods.go, uchiwa/sensu/request.go
Signed-off-by: Justin Kolberg <amd.prophet@gmail.com>
Prevents HTTP status codes less than 500 from marking an API as unhealthy.
See #815.
I browsed through Uchiwa & tried URLs for non-existent clients. More testing is still needed.
=> 4xx errors should not mark api as unhealthy
