public/js/filters.js

Fix https://github.com/sensu/uchiwa/issues/247
CC @amdprophet

Verify the boolean type on richOutput function

---

public/index.html
public/js/controllers.js
public/js/filters.js
public/js/services.js
public/partials/stash-modal.html
public/partials/stashes/index.html
test/karma/filters-spec.js

Add custom date functionality in create stash modal.

Add custom date functionality

---

public/js/filters.js

Useful until better support for external components has been added.

allow iframes in richOutput

---

public/index.html

Related to https://github.com/sensu/uchiwa-web/pull/6

Include navbar and sidebar from partials

---

public/index.html

See https://github.com/sensu/uchiwa-web/pull/10

Remove init controller

---

public/index.html

Required for https://github.com/sensu/uchiwa-web/pull/28

Add angular-moment

---

auth/auth.go
auth/drivers.go
auth/handlers.go
auth/roles.go
auth/token.go
uchiwa.go
uchiwa/config.go
uchiwa/dc.go
uchiwa/server.go

- Import auth package within Uchiwa repo
- Add support of GitHub driver (Sensu Enterprise)

Import auth package within Uchiwa repo

---

uchiwa/aggregate.go
uchiwa/client.go
uchiwa/helpers.go
uchiwa/helpers_test.go
uchiwa/server.go
uchiwa/stashes.go

Fix https://github.com/sensu/uchiwa/issues/301

Use stash struct for /stashes requests

---

uchiwa/stashes.go

Fix https://github.com/sensu/uchiwa/issues/319

Omit expire attribute of stash struct when empty

---

.gitignore
uchiwa/client.go

Displays output for all checks, if available. Tested on Sensu 0.13.0 and 0.18.0
Closes https://github.com/sensu/uchiwa/issues/322

Show last_status output

---

uchiwa/daemon/clients.go

Fix https://github.com/sensu/uchiwa/issues/337

Only convert the event's check to a struct

---

uchiwa/config/config_test.go

First time playing with Go and playing with other test I found that this file had reverse "expected" and "actual" in assert. Patch to fix this :)

Reverse expected vs actual

---

fixtures/config_test_multiple.json
uchiwa.go
uchiwa/auth/auth.go
uchiwa/auth/drivers.go
uchiwa/config/config.go
uchiwa/config/config_test.go

Add the possibilities of having more than one user/password and even use the other flag from the Role such as readonly taken into account. I'm pretty sure this is needed in most installation where we don't want anyone to have access to silence checks, etc...

We can have multiple users with different "role"

---

uchiwa/server.go

Fix https://github.com/sensu/uchiwa/issues/352

Display any error with the http.ListenAndServe function

---

uchiwa/server.go
uchiwa/stash.go

Fix https://github.com/sensu/uchiwa/issues/356

Add username to stash content

---

uchiwa.go
uchiwa/daemon/clients.go
uchiwa/daemon/daemon.go
uchiwa/daemon/helpers.go
uchiwa/daemon/helpers_test.go
uchiwa/daemon/results.go
uchiwa/daemon/results_test.go
uchiwa/filters/filters.go
uchiwa/main.go
uchiwa/sensu/results.go
uchiwa/server.go
uchiwa/structs/structs.go

- Add support for the /results Sensu API endpoint
- Add basic endpoints for _GET_ requests to reflect Sensu API

Add support for Sensu Enterprise dashboard

---

.gitignore
uchiwa/client.go
uchiwa/client_test.go
uchiwa/daemon/clients.go
uchiwa/daemon/events.go
uchiwa/daemon/helpers.go
uchiwa/helpers/helpers.go
uchiwa/helpers/helpers_test.go

Fix https://github.com/sensu/uchiwa/issues/395
Related to https://github.com/sensu/uchiwa-web/pull/78

Refactoring client history

---

Gruntfile.js
public/index.html

Related to https://github.com/sensu/uchiwa-web/pull/85

Upgrade angular-toastr to 1.6.0

---

uchiwa/check.go
uchiwa/daemon/checks.go
uchiwa/daemon/checks_test.go
uchiwa/daemon/daemon.go
uchiwa/sensu/checks.go
uchiwa/server.go
uchiwa/structs/structs.go

Fix https://github.com/sensu/uchiwa/issues/141

Add support for issuing check requests

---

uchiwa/results.go
uchiwa/sensu/results.go
uchiwa/server.go

**Depends on Sensu Core 0.21**

Add support for deleting client check results

---

uchiwa/sensu/methods.go

Fix https://github.com/sensu/uchiwa/issues/438

Prevent infinite pagination loop

---

uchiwa/aggregate.go
uchiwa/daemon/aggregates.go
uchiwa/daemon/aggregates_test.go
uchiwa/daemon/daemon.go
uchiwa/sensu/aggregates.go
uchiwa/server.go

See https://github.com/sensu/sensu/pull/1273

Add support for aggregates 2.0

---

check_test.go
uchiwa/aggregate.go
uchiwa/aggregate_test.go
uchiwa/check.go
uchiwa/client.go
uchiwa/client_test.go
uchiwa/server.go
uchiwa/stash.go
uchiwa/stash_test.go

Relates to https://github.com/sensu/uchiwa-web/pull/102

Uchiwa API refactoring

---

uchiwa/server.go

Fix https://github.com/sensu/uchiwa/issues/512

Return an empty slice instead of null

---

uchiwa/daemon/subscriptions.go
uchiwa/daemon/subscriptions_test.go

Fix https://github.com/sensu/uchiwa/issues/534

Do not include per-client subscriptions in the subscriptions filter

---

uchiwa/filters/filters.go
uchiwa/server.go

Fix https://github.com/sensu/uchiwa/issues/543

Fix race condition when using the Uchiwa filters

---

uchiwa/client.go
uchiwa/client_test.go
uchiwa/daemon/clients.go
uchiwa/daemon/daemon.go
uchiwa/daemon/events.go
uchiwa/daemon/metrics.go
uchiwa/daemon/silenced.go
uchiwa/filters/filters.go
uchiwa/helpers.go
uchiwa/helpers/helpers.go
uchiwa/helpers/helpers_test.go
uchiwa/sensu/silenced.go
uchiwa/server.go
uchiwa/silenced.go
uchiwa/structs/structs.go

**Requires Sensu <= 0.26**
Fix https://github.com/sensu/uchiwa/issues/539, https://github.com/sensu/uchiwa/issues/542

Replace silence stashes with built-in Sensu silencing

---

uchiwa/server.go

Fix https://github.com/sensu/uchiwa/issues/557

The /health endpoint can return a 503 HTTP response code on error

---

public/index.html
uchiwa/daemon/subscriptions.go
uchiwa/daemon/subscriptions_test.go
uchiwa/filters/filters.go
uchiwa/server.go
uchiwa/structs/structs.go

Use all features from built-in silencing in Sensu 0.26
- Silence subscriptions
- Silence checks across a datacenter

Rich Silencing

---

Gruntfile.js
public/index.html
uchiwa/daemon/daemon.go
uchiwa/daemon/helpers.go

Required by https://github.com/sensu/uchiwa-web/pull/120

Refactoring of frontend services

---

uchiwa/server.go

Fixes https://github.com/sensu/uchiwa/issues/590
Fixes https://github.com/sensu/uchiwa/issues/529

Prevent any caching of the index.html file

---

uchiwa/helpers/helpers.go
uchiwa/helpers/helpers_test.go

Healthy clients should be displayed in the clients popover.
sensu/uchiwa#607

Count healthy clients in metrics. Fixes #607

---

Gruntfile.js
public/index.html

Add support for responsive web design

---

uchiwa/config/config.go
uchiwa/config/structs.go
uchiwa/helpers/helpers.go
uchiwa/helpers/helpers_test.go

* Add support for the OIDC configuration
* Add helpers methods
* Use a constant for obfuscating sensible variables

[enterprise] Add support for OpenID Connect

---

uchiwa/authentication/accessToken.go
uchiwa/authentication/controllers.go
uchiwa/authentication/jwt.go
uchiwa/authentication/services.go
uchiwa/authorization/authorization.go
uchiwa/authorization/authorization_test.go
uchiwa/helpers/helpers.go
uchiwa/helpers/helpers_test.go
uchiwa/server.go

Resolves https://github.com/sensu/uchiwa/issues/638
* The authentication cookie storing the JWT use the `Httponly` flag
* An authentication cookie named `XSRF-TOKEN` is provided to Angular

Add CSRF protection to JWT

---

uchiwa/authentication/controllers.go
uchiwa/server.go

Related to https://github.com/sensu/uchiwa-web/pull/142

[enterprise] Implement audit logging in the backend

---

uchiwa/authentication/controllers.go
uchiwa/authentication/services.go

Provides additional security when HTTPS protocol is used.
Fixes https://github.com/sensu/uchiwa/issues/656
Manual testing with both HTTP & HTTPS protocol

Set the Secure flag on authentication coookies for TLS connections

---

public/index.html
uchiwa/config/structs.go

Adds a new attribute `favicon` within UsersConfig to allow customization of the favicon. 
Fixes https://github.com/sensu/uchiwa/issues/606
Depends on https://github.com/sensu/uchiwa-web/pull/146

Allow custom favicon

---

uchiwa/check.go
uchiwa/helpers/helpers.go
uchiwa/helpers/helpers_test.go
uchiwa/server.go

Adds a check view so all attributes of a check can be viewed from Uchiwa.
Fixes https://github.com/sensu/uchiwa/issues/672
Requires https://github.com/sensu/uchiwa-web/pull/153

Add a check view

---

uchiwa/authentication/jwt.go
uchiwa/config/structs.go

Adds additional configuration attributes in the OIDC scope for Okta support
https://github.com/sensu/sensu-enterprise-dashboard/issues/105

[Enterprise] Support for Okta

---

uchiwa/structs/structs.go

Add information about Sensu server tasks and other information added in [Sensu 0.29](https://github.com/sensu/sensu/blob/master/CHANGELOG.md#0290---2017-03-29).
Closes https://github.com/sensu/uchiwa/issues/706

Add Sensu server tasks and more to datacenter view

---

Dockerfile

It updates the Docker base image to golang:1.9.2-alpine
Closes https://github.com/sensu/uchiwa/issues/731
Fixes the docker builds

Update the Docker base image to golang:1.9.2-alpine

---

.rpmmacros
.travis.yml
build/Rakefile
build/setup-gpg
build/sign-rpm

Sign the Uchiwa RPM package with the Sensu package GPG key.

Sign RPM packages

---

uchiwa/config/config.go
uchiwa/config/config_test.go

Resolves #772.
This is my first stab at developing in Go, so let me know if this isn't very conventional.

Pull PORT from the environment if available

---

uchiwa/helpers/helpers.go
uchiwa/silenced.go

Closes https://github.com/sensu/uchiwa/issues/769

Add scheduled maintenance
